---
Customs:
- 5938188786f77474f723e87f  # Case 0031
- 5c12301c86f77419522ba7e4  # Flash drive with fake info
- 593965cf86f774087a77e1b6  # Case 0048
- 591092ef86f7747bb8703422  # Secure folder 0022 in big red offices
- 590c62a386f77412b0130255  # Sliderkey Secure Flash drive in Dorms 2-way room 220
- 5939e9b286f77462a709572c  # Sealed letter (Terragroup)
- 5ac620eb86f7743a8e6e0da0  # Package of graphics cards in big red offices
- 590dde5786f77405e71908b2  # Bank case
- 5910922b86f7747d96753483  # Carbon case
- 5937fd0086f7742bf33fc198  # Bronze pocket watch on a chain
- 5939a00786f7742fe8132936  # Golden Zibbo lighter
- 5939e5a786f77461f11c0098  # Secure Folder 0013
- 64e74a3d4d49d23b2c39d319 # item_quest_clock_07 (Out of Time)
#- 64bd1abff3a668f08805ce4f  # Secure Flash drive V4 REMOVED BY BSG

Woods:
- 5938878586f7741b797c562f  # Case 0052
- 5d3ec50586f774183a607442  # Jaeger's message Underneath the wooden lookout post.
- 5af04e0a86f7743a532b79e2  # Single-axis Fiber Optic Gyroscope: item_barter_electr_gyroscope
- 5a687e7886f7740c4a5133fb  # Blood sample
- 5af04c0b86f774138708f78e  # Motor Controller: item_barter_electr_controller
#- 64bde2248f3a947a990aa4a5  # Sliderkey Secure Flash drive #1 REMOVED BY BSG
#- 64bde265807321a9b905f076  # Sliderkey Secure Flash drive #2 REMOVED BY BSG

Shoreline:
- 5a294d7c86f7740651337cf9  # Drone 1 SAS disk
- 5a294d8486f774068638cd93  # Drone 2 SAS disk: ambiguous with itemTpl 5a294f1686f774340c7b7e4a
- 5efdafc1e70b5e33f86de058  # Sanitar's Surgery kit marked with a blue symbol
- 5939e5a786f77461f11c0098  # Secure folder 0013
- 5a6860d886f77411cd3a9e47  # Secure folder 0060
- 5a29357286f77409c705e025  # Sliderkey Flash drive
- 5efdaf6de6a30218ed211a48  # Sanitar's Ophthalmoscope In potted plant on dining room table.
- 5d357d6b86f7745b606e3508  # Photo album in west wing room 303
- 5b4c72b386f7745b453af9c0  # Motor Controller: item_barter_electr_controller2
- 5a0448bc86f774736f14efa8  # Key to the closed premises of the Health Resort
- 5a29276886f77435ed1b117c  # Working hard drive
- 5b4c72fb86f7745cef1cffc5  # Single-axis Fiber Optic Gyroscope: item_barter_electr_gyroscope2
- 5b4c72c686f77462ac37e907  # Motor Controller: item_barter_electr_controller3
- 5b43237186f7742f3a4ab252  # Chemical container: item_quest_chem_container
- 5a29284f86f77463ef3db363  # Toughbook reinforced laptop
- 64e74a534d49d23b2c39d31b # item_quest_clock_10 (Out of Time)

Interchange:
- 5ae9a18586f7746e381e16a3  # OLI cargo manifests
- 5ae9a0dd86f7742e5f454a05  # Goshan cargo manifests
- 5ae9a1b886f77404c8537c62  # Idea cargo manifests
- 5ae9a25386f7746dd946e6d9  # OLI cargo route documents (locked)
- 5ae9a3f586f7740aab00e4e6  # Clothes design handbook - Part 1
- 5ae9a4fc86f7746e381e1753  # Clothes design handbook - Part 2
- 5b4c81a086f77417d26be63f  # Chemical container item_quest_chem_container2
- 5b4c81bd86f77418a75ae159  # Chemical container item_quest_chem_container3
- 64e74a5ac2b4f829615ec336 # item_quest_clock_11 (Out of Time)

Factory:
- 591093bb86f7747caa7bb2ee  # On the neck of the dead scav in the bunker (Postman Pat Part 2)
- 593a87af86f774122f54a951  # Syringe with a chemical

Lighthouse:
- 61904c9df62c89219a56e034  # The message is tucked under the bottom of the door to the cabin.
- 619268ad78f4fa33f173dbe5  # Water pump operation data On the desk between other documents in the upper office.
- 619268de2be33f2604340159  # Pumping Station Operation Data In the upper floor office on the shelf.
- 61a00bcb177fb945751bbe6a  # Stolen military documents On the back corner of the dining room table on the third floor at Chalet.
- 619252352be33f26043400a7  # Laptop with information
- 628393620d8524273e7eb028  # Working hard drive
- 6331bb0d1aa9f42b804997a6  # V3 Flash Drive
- 6398a0861c712b1e1d4dadf1  # Forged Lightkeeper intelligence (Snatch)
- 6399f54b0a36db13c823ad21  # Radio transmitter body (Key to the Tower)
- 64e74a64aac4cd0a7264ecdf # item_quest_clock_12 (Out of Time)
# - 64b91627dd13d43b9d01d6d1  # Toughbook reinforced laptop (Event quest) REMOVED BY BSG

ReserveBase:
- 60915994c49cf53e4772cc38  # Military documents 1 on the table inside bunker control room (Documents)
- 60a3b6359c427533db36cf84  # Military documents 2 On the bottom shelf of the cupboard near the corner.
- 60a3b65c27adf161da7b6e14  # Military documents 3 Inside the cupboard next to the 4x4 Weapon Box.
- 608c22a003292f4ba43f8a1a  # Medical record 1 (locked by RB-KSM key) (Disease history)
- 60a3b5b05f84d429b732e934  # Medical record 2 (locked by RB-SMP key) Disease history)
- 609267a2bb3f46069c3e6c7d  # T-90M Commander Control Panel
- 60c080eb991ac167ad1c3ad4  # MBT Integrated Navigation System
- 6398a072e301557ae24cec92  # Original Lightkeeper Intelligence (Snatch)
- 64e74a4baac4cd0a7264ecdd # item_quest_clock_09 (Out of Time)

Laboratory:
- 5eff135be0d3331e9d282b7b  # Flash drive marked with blue tape (TerraGroup employee)
- 6398a4cfb5992f573c6562b3  # Secured tape
- 64e74a44c2b4f829615ec334 # item_quest_clock_08 (Out of Time)
#- 64bdcfed8f3a947a990aa49a  # Hermetic container for storing various chemicals #1 REMOVED BY BSG
#- 64bdd008b0bf3baa6702f35f  # Hermetic container for storing various chemicals #2 REMOVED BY BSG
#- 64bdd014f3a668f08805ce64  # Hermetic container for storing various chemicals #3 REMOVED BY BSG

Streets of Tarkov:
- 63a943cead5cc12f22161ff7  # Accountant's notes (Audit)
- 638cbc68a63f1b49be6a3010  # Registered letter (Youve Got Mail)
- 638df4cc7b560b03794a18d2  # AG guitar pick (Audiophile)
- 638e0057ab150a5f56238960  # Housing office journal (Population Census)
- 63927b29c115f907b14700b9  # Chemical container with samples (Urban Medicine)
- 638dfc803083a019d447768e  # Working hard drive (Surveillance)
- 638e9d5536b3b72c944e2fc7  # Flash drive with recordings (Watching You)
- 6393262086e646067c176aa2  # Medical observation record (?)
- 63989ced706b793c7d60cfef  # Informant's journal (Missing Informant)
- 638cbb3ba63f1b49be6a300e  # Secure Flash drive (Your Car Needs a Service)
- 63a39e1d234195315d4020bd  # Primorsky 46-48 skybridge key
- 64e73909cd54ef0580746af3 # item_quest_clock_01 (Out of Time)
- 64e74a186393886f74114a96 # item_quest_clock_02 (Out of Time)
- 64e74a1faac4cd0a7264ecd9 # item_quest_clock_03 (Out of Time)
- 64e74a274d49d23b2c39d317 # item_quest_clock_04 (Out of Time)
- 64e74a2fc2b4f829615ec332 # item_quest_clock_05 (Out of Time)
- 64e74a35aac4cd0a7264ecdb # item_quest_clock_06 (Out of Time)
- 64f09c02b63b74469b6c149f # Paramedic's GPhone X (Ambulances Again)
- 64f07f7726cfa02c506f8ac0 # Journal item_quest_kpss2 (Glory To CPSU P2)
- 64f69b4267e11a7c6206e010 # Chef's diary (Beyond the Red Meat - Part 1)
- 64f5b4f71a5f313cb144c06c # Secret component (Beyond the Red Meat - Part 2)

Sandbox:
- 6582bd252b50c61c565828e2 # Bottle of Le Jean wine